version: '3.9'
services:
  db:
    image: postgres:15
    container_name: swift_db
    env_file:
      - .env
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: swift_api
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"